spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/mysql
    username: root
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8881

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.67.128:8761/eureka/

